### ISSUE TITLE
error running calculateCNVs.py

### ISSUE THREAD

**Issue by Gon1976** [kathryncrouch/geneCNVs#1]
Hi, I am trying to run calculateCNVs.py and I have this error:
Traceback (most recent call last):
  File "/CNV/calculateCNVs.py", line 34, in <module>
    if __name__=="__main__": __main__()
  File "/CNV/calculateCNVs.py", line 21, in __main__
    GeneModels = GffParser(args.genome)
  File "/CNV/TPMtool/TPMtool.py", line 16, in __init__
    self.transcriptParents = self._getTranscriptParents()
  File "/CNV/TPMtool/TPMtool.py", line 33, in _getTranscriptParents
    if fields[self.featureTypeCol] == 'transcript' or fields[self.featureTypeCol].endswith('RNA'):
IndexError: list index out of range

My command line to get htseq is:
htseq-count -t CDS -q -f bam -r pos -i File.markdup.bam genomic.gff > File.htseq.CDS.out

and for calculateCNV
./calculateCNVs.py --genome genomic.gff --input File.htseq.CDS.out --outputPrefix CNV

**Comment by Gon1976** [comment]
there was an error in the gff file
